media:
  input: public/assets
  output: /assets
  categories: [ "image", "document", "audio"]

content:

  - name: works
    label: Works
    type: collection
    path: _works
    view:
      fields: [ title, year]
      primary: title
      sort: [ year, title ]
      default:
        sort: year
        order: desc
    fields:
      - name: slug
        label: Slug
        type: string
        description: "URL-friendly version of the title"
        required: true
      - name: title
        label: Title
        type: string
        description: "Needs to be unique from title of any other project, otherwise pages will collide."
        required: true
      - name: year
        label: Year
        type: number
      - name: headerImageUrl
        label: Project Image
        type: image
        list: false
        description: "The project header image"
      - name: carouselImages
        label: Project Images
        type: object
        list: true
        fields:
          - name: url
            label: Image URL
            type: image
            required: true
          - name: caption
            label: Image Caption
            type: string
            description: "Optional caption for this image"
        description: "Project images for carousel - carousel is placed at the page bottom"
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html
      - name: references
        label: References
        type: object
        list: true
        fields:
          - name: reference-number
            label: Reference Number
            type: number
            required: true
            default: "{index+1}"  # This will use the index position in the array
          - name: reference
            label: Reference Content
            type: rich-text
            list: true


  - name: about
    label: About
    type: file
    path: about.md
    format: yaml-frontmatter
    fields:
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html

  - name: cv
    label: CV
    type: file
    path: CV.md
    format: yaml-frontmatter
    fields:
      - name: sections
        label: CV Sections
        type: object
        list: true
        fields:
          - name: title
            label: Section Title
            type: string
            required: true
          - name: items
            label: Section Items
            type: text
            list: true
      - name: body
        label: Content
        type: rich-text
        description: "Use '/' to activate commands, mark text to edit it to links or style it. Also, importantly, for spacing between paragraphs use 2x 'shift+enter'."
        options:
          format: html